export enum ProductCat_Enum {
    Food = "Food",
    Clothes = "Clothes",
    Electronics = "Electronics",
    Books = "Books",
    Other = "Other",
    Toys = "Toys",
    Furniture = "Furniture",
    Sports = "Sports",
    Vehicles = "Vehicles",
    Pets = "Pets",
    Services = "Services",
    Jobs = "Jobs",
    RealEstate = "RealEstate",
    Films = "Films",
    Music = "Music",
    Games = "Games",
    Art = "Art",
    Collectibles = "Collectibles",
    HomeGarden = "HomeGarden",
    Tools = "Tools",
    HealthBeauty = "HealthBeauty",
    BusinessIndustrial = "BusinessIndustrial",
    Travel = "Travel",

}